class_name data_story_id

var main_data = {
	"bab_1":"Di tepi sebuah perkampungan, berdiri hutan lebat yang selalu diselimuti kabut, seolah cahaya siang pun enggan menembusinya. Pohon-pohon tumbuh rapat, akar menjerat tanah, dan udara lembap membawa aroma basah yang tak pernah hilang. Hutan itu tampak subur, namun justru memberi kesan hidup yang menyimpan rahasia. Penduduk percaya bahwa siapa pun yang masuk terlalu jauh hanya meninggalkan nama, hilang tanpa jejak seakan ditelan oleh kesunyian. Bagi mereka, hutan itu bukan sekadar kisah lama, melainkan misteri nyata yang terus menghantui, seolah ada sesuatu yang menunggu di balik kabut pekat.",
	"bab_2":"kehidupan yang mampu bertahan. Namun di balik gelombang pasir yang selalu berubah, berdiri sebuah benteng raksasa menjulang ke langit. Dindingnya kokoh, seakan menantang waktu dan badai padang pasir. Di dalamnya, tersembunyi denyut kehidupan—jalan sempit, rumah-rumah batu, hingga pasar yang berisik—membentuk sebuah kota yang masih bertahan melawan kehampaan di luar. Bagi para penyintas, benteng itu adalah tempat terakhir, satu-satunya perlindungan dari alam yang terus berusaha menghapus jejak manusia dari gurun yang tak mengenal ampun.",
	"bab_3":"Di sebuah dataran es yang sunyi dan kejam, udara tipis membuat setiap tarikan napas terasa seperti pertarungan melawan waktu. Hamparan putih membentang tanpa akhir, namun di balik kerasnya dingin tersembunyi kekayaan langka: emas yang membeku dalam urat tanah, batu bara hitam terperangkap di bawah lapisan beku, hingga kristal mana yang berkilau samar seakan bernapas sendiri. Tempat itu seolah menyimpan rahasia purba, peninggalan masa lalu yang tak pernah terungkap. Namun suhu membekukan, badai tak berkesudahan, dan oksigen yang menipis menjadikannya makam alamiah bagi siapa pun yang mencoba menguak misterinya.",
	"bab_4":"Jauh di dalam perut bumi, tersembunyi sebuah dunia yang hampir tak pernah tersentuh manusia. Kegelapan pekat menyelimuti setiap sudut, hanya diterangi oleh cahaya samar dari mineral bercahaya dan aliran sungai bawah tanah yang berkilau seperti kaca hitam. Hutan jamur raksasa tumbuh liar, makhluk aneh beradaptasi tanpa mata, dan udara dipenuhi gema asing dari kedalaman tak terukur. Tempat itu terasa asing, seakan berdiri di luar hukum alam permukaan. Sebuah kehidupan yang sunyi namun penuh misteri, seolah abyss itu menyimpan rahasia yang menunggu untuk ditemukan, atau mungkin lebih baik tetap tersembunyi.",
	"bab_5":"Di balik dinding tinggi dan menara berasap, berdiri sebuah kota yang dipenuhi para ilmuwan gila. Setiap sudutnya bergema oleh suara mesin, dentuman logam, dan percikan listrik dari percobaan yang tak pernah berhenti. Jalan-jalan dipenuhi laboratorium, tempat di mana ide liar diwujudkan tanpa peduli batas moral. Dari ruang-ruang gelap lahirlah ciptaan aneh: humanoid hibrid dengan tubuh setengah mesin, setengah daging, yang berkeliaran sebagai bukti kesombongan pengetahuan. Kota ini menjadi pusat kecerdasan sekaligus kegilaan, sebuah tempat di mana masa depan dan mimpi buruk berjalan berdampingan.",
	"bab_6":"Tinggi di atas awan, berdiri sebuah kerajaan langit yang memancarkan keindahan seakan lahir dari mimpi. Istana-istana menjulang, dibangun dari kristal bening dan logam berkilau yang memantulkan cahaya matahari, hingga seluruh langit tampak bersinar. Jalanan terapung dihubungkan oleh jembatan cahaya, sementara taman-taman menggantung penuh bunga berwarna lembut yang tak pernah layu. Burung-burung raksasa dan makhluk bersayap terbang bebas di udara, menjadi penjaga alami kerajaan ini. Dari ketinggian, dunia bawah terlihat kecil dan jauh, seolah hanya bayangan. Tempat itu adalah simbol kemegahan dan harmoni, sebuah surga yang melayang di antara langit biru.",
	"bab_7":"Di celah antar dimensi, tersembunyi sebuah kerajaan kuno yang tak terjamah cahaya, dikenal hanya dalam bisikan sebagai takhta para iblis purba. Gerbang menuju tempat itu konon muncul sebagai retakan hitam di udara, membawa aroma belerang dan gema suara asing dari kegelapan. Istana menjulang dari batu obsidian, dihiasi api abadi yang tak pernah padam, sementara bayangan besar bergerak di balik dindingnya. Di dalamnya, berdiri para penguasa iblis dengan kekuatan yang mengikat waktu dan jiwa. Kerajaan ini bukan sekadar tempat, melainkan luka kosmos—sebuah misteri yang terus berdenyut di antara dimensi, menunggu jiwa-jiwa yang tersesat untuk ditelan.",
}
