class_name data_story_char_s1_75

var desc_dark_en = "A frail creature born from remnants of dark energy. Its body is thin and wavering, resembling a wisp of black smoke shaped like a small humanoid, with dim crimson eyes. Though weak, it attacks with shadowy claws and shrouds enemies in a haze of darkness to disrupt their vision. These monsters often appear in swarms, relying on numbers to overwhelm, as a single one is easily dispelled by light. They are but fragments of a greater dark soul, a sign that something far stronger lurks within the shadows."


var hero_1 = {
	"id":"Seorang wanita lahir dari garis keturunan yang terpecah, darah elf yang suci bercampur dengan kegelapan iblis. Ia tumbuh dalam pandangan curiga dari banyak pihak, namun memilih jalan sebagai pemanah yang menguasai panah darah—senjata yang menyalurkan kehidupannya sendiri sebagai kekuatan. Sayap hitam di punggungnya menjadi simbol beban dan anugerah, membuatnya terbang di antara cahaya dan bayangan, selalu mencari alasan keberadaannya.",
	"en":"Born from a divided lineage, the purity of elf blood mixed with the darkness of demons. She grew up under the weight of suspicion, yet chose the path of an archer, wielding blood arrows that draw strength from her very life. The black wings on her back serve as both burden and blessing, allowing her to soar between light and shadow, forever seeking the meaning of her existence."
}
var hero_8 = {
	"id":"Seorang wanita iblis dengan pesona yang memikat, namun di balik kecantikannya tersembunyi naluri mematikan. Sejak kecil ia dilatih untuk membunuh dalam senyap, menjadikan belati sebagai perpanjangan tangannya. Gerakannya cepat, senyap, dan penuh perhitungan. Baginya, setiap tusukan bukan hanya tugas, melainkan seni yang menegaskan eksistensinya di dunia yang penuh intrik dan kegelapan.",
	"en":"A beautiful demon woman, her allure masks a deadly instinct. Trained from an early age to kill in silence, she mastered daggers until they became an extension of her own body. Her movements are swift, precise, and soundless, each strike delivered with cold calculation. For her, every kill is not merely a task, but an art form that affirms her place within a world of shadows and deceit."
}
var hero_9 = {
	"id":"Seorang wanita cantik yang dikenal sebagai assassin, namun keunikannya terletak pada kekuatan sihir ular yang menjalar di tubuhnya. Dengan sebuah tongkat sihir di tangan, ia mampu memanggil ilusi berbisa maupun ular nyata untuk melumpuhkan musuhnya. Keanggunannya menipu lawan, sementara setiap gerakan membawa ancaman tersembunyi. Antara bayangan dan racun, ia menjadikan keheningan sebagai panggung kematian.",
	"en":"A beautiful woman known as an assassin, yet her true power lies in serpent magic coursing through her veins. Wielding a staff, she conjures venomous illusions and serpents to paralyze her prey. Her elegance deceives, masking the peril behind every movement. Between shadows and poison, she transforms silence into a stage of death, where each strike is both graceful and merciless."
}
var hero_10 = {
	"id":"Seorang iblis assassin berkulit pucat, wajahnya menyeramkan dengan mulut besar dan lidah yang sangat panjang. Dalam gelap, ia bergerak tanpa suara, memburu mangsanya dengan kesabaran mengerikan. Lidahnya bukan hanya alat intimidasi, tetapi senjata mematikan yang mampu mencekik atau melumpuhkan. Pucat tubuhnya menyatu dengan bayangan, menjadikannya momok yang sulit dilihat hingga saat terakhir.",
	"en":"A pale-skinned demon assassin, his face twisted with a wide mouth and a grotesquely long tongue. In darkness, he moves without sound, stalking prey with terrifying patience. His tongue is more than intimidation—it is a weapon, strangling or disabling victims in silence. His pallid form blends seamlessly with the shadows, making him an unseen terror until the final, fatal moment."
}
var hero_11 = {
	"id":"Iblis putih menyeramkan ini memiliki kulit sekeras baja, tampak seperti lapisan armor alami yang menutupi seluruh tubuhnya. Setiap langkahnya menimbulkan aura dingin yang menusuk, sementara cakarnya yang panjang dan tajam mampu merobek baja maupun daging dengan mudah. Sosoknya bagaikan mimpi buruk yang lahir dari kegelapan, diam namun penuh ancaman, selalu menunggu saat tepat untuk menerkam.",
	"en":"This terrifying white demon bears skin like steel, forming a natural armor that shields its entire body. Each step radiates a chilling aura, while its long, razor-sharp claws can shred through both flesh and metal with ease. It stands as a nightmare given form—silent yet menacing—ever waiting for the perfect moment to strike with ruthless precision."
}
var hero_12 = {
	"id":"Sejak kecil ia menyaksikan keluarganya hancur oleh pengkhianatan, meninggalkan luka batin yang tak pernah sembuh. Tumbuh dalam bayang-bayang kebencian, ia belajar bahwa dunia hanya mengenal kekuatan. Katana menjadi temannya, bayangan menjadi rumahnya. Dari trauma itu lahirlah tekad: menjadi pembunuh bayaran yang hidup di antara darah dan bisikan malam. Wajah cantiknya hanya topeng, menyembunyikan jiwa yang dipahat oleh kehilangan.",
	"en":"As a child, she watched her family destroyed by betrayal, leaving scars that never healed. Growing within shadows of hatred, she learned the world respected only strength. The katana became her companion, the darkness her home. From that trauma, she forged her path as a mercenary assassin, living between blood and whispers of the night. Her beauty is but a mask, concealing a soul shaped by loss."
}
var hero_13 = {
	"id":"Seorang ratu iblis yang lahir dari peperangan dan pengkhianatan, tumbuh dengan keyakinan bahwa hanya kekuatan yang bisa menjaga singgasananya. Sabit besar di tangannya bukan sekadar senjata, melainkan simbol dari kematian dan kekuasaan. Setiap ayunan membawa aura kegelapan yang menelan harapan. Meski keindahan dan wibawanya memikat, matanya menyimpan beban masa lalu—kenangan akan darah dan kehancuran yang membentuknya menjadi penguasa tanpa ampun.",
	"en":"A demon queen born from war and betrayal, she grew to believe that only power could secure her throne. The scythe she wields is not just a weapon, but a symbol of death and dominion. Each swing radiates darkness that devours hope. Though her beauty and presence are mesmerizing, her eyes carry the weight of the past—memories of blood and ruin that forged her into a merciless sovereign."
}
var hero_14 = {
	"id":"Sosok iblis pucat ini muncul bagaikan mimpi buruk, tubuhnya menjulang dengan tanduk tajam dan empat sayap gelap yang membentang lebar. Dari masa kecilnya, ia dianggap aib bahkan di kalangan iblis, sehingga tumbuh dalam kesepian dan kebencian. Luka batin itu berubah menjadi kekuatan mengerikan; setiap sayapnya menyimpan kekuatan destruktif yang mampu melahap cahaya. Kini ia menjelma makhluk menakutkan, simbol dari kegelapan yang menolak dilupakan.",
	"en":"This pale demon emerges like a living nightmare, towering with jagged horns and four vast, black wings. From childhood, even among demons, it was branded an outcast, growing in solitude and resentment. That inner wound twisted into dreadful power; each wing carries destructive force capable of devouring light itself. Now it stands as a fearsome entity—a symbol of darkness that refuses to be forgotten."
}
var hero_15 = {
	"id":"Seorang ratu assassin terkuat, darah elf yang mengalir di tubuhnya memberi keanggunan sekaligus kutukan. Dari masa kecilnya ia diburu karena garis keturunannya, hingga terpaksa bertahan dengan pisau di tangan. Trauma itu menumbuhkan tekad untuk menguasai bayangan. Kini, dengan sihir ungu yang berdenyut di nadinya dan dua pedang ungu yang menjadi perpanjangan jiwanya, ia menjelma penguasa bayangan yang tak tertandingi, indah sekaligus mematikan.",
	"en":"The strongest assassin queen, her elven blood grants both grace and curse. Hunted since childhood for her lineage, she survived only with blades in her hands. That trauma forged her resolve to master the shadows. Now, with violet magic pulsing through her veins and two purple swords as extensions of her soul, she has become an unrivaled sovereign of the night—beautiful, yet mercilessly lethal."
}
var hero_24 = {
	"id":"Iblis ini tampak mengerikan, dengan tulang keras yang tumbuh keluar dari tubuhnya, membentuk perisai alami di kepala dan sayap. Dari masa kecilnya ia dianggap sebagai makhluk terkutuk, tubuhnya terus berubah dengan rasa sakit tiada henti. Namun penderitaan itu justru menempanya menjadi sosok yang nyaris tak tertembus. Setiap tulang yang menonjol adalah jejak luka masa lalu, kini menjelma senjata sekaligus pertahanan, menjadikannya simbol horor yang lahir dari penderitaan.",
	"en":"This demon is terrifying, with bone protrusions growing from its body, forming natural shields across its head and wings. As a child, it was shunned as a cursed being, its body twisting in endless agony. Yet that torment forged it into an almost unbreakable creature. Every exposed bone is a scar of its past suffering, now turned into both weapon and armor—an embodiment of horror born from pain itself."
}
var hero_25 = {
	"id":"Seorang iblis wanita cantik dengan tubuh rapuh seolah akan runtuh kapan saja, namun justru di situlah letak kekuatannya. Sejak kecil ia dikutuk dengan darah yang mendidih, setiap tetesnya menyimpan energi mengerikan. Meski tampak lemah, darah itu memberinya kekuatan melampaui batas, menjadikan tubuh rapuhnya sekadar ilusi. Di balik senyumnya yang tenang, ia mampu mengubah kelemahan menjadi senjata, menjelma sosok mematikan yang tak terduga.",
	"en":"A beautiful demon woman, her body appears fragile as if it might collapse at any moment, yet within lies her greatest strength. Cursed since childhood with boiling blood, every drop carries terrifying energy. Though she seems weak, that blood grants her power beyond limits, making her frailty nothing but an illusion. Behind her calm smile, she turns weakness into a weapon, becoming a deadly force none would expect."
}
var hero_26 = {
	"id":"Seorang raja iblis bertubuh raksasa, tubuhnya menjulang seperti benteng hidup. Sejak muda ia ditempa dalam medan perang, bukan untuk menyerang, melainkan untuk bertahan. Kulitnya sekeras batu, ototnya seperti baja, membuatnya dijuluki perisai terakhir kaum iblis. Di balik kekuatan itu, ia memikul beban masa lalu: sumpah untuk melindungi kaumnya setelah menyaksikan kehancuran bangsanya. Kini ia menjadi tembok yang tak tergoyahkan, simbol pertahanan yang abadi.",
	"en":"A massive demon king, his body towers like a living fortress. From youth, he was forged on the battlefield, not as a weapon of destruction but as the ultimate defense. His skin is stone-like, his muscles steel, earning him the title of the demons’ final shield. Yet behind that power lies a vow—born from the ruins of his people—to protect his kin at any cost. Now he stands as an unyielding wall, the eternal symbol of defense."
}
var hero_27 = {
	"id":"Seorang wanita elf cantik yang sejak kecil dianugerahi bakat penyembuh, namun berbeda dari kaumnya, ia tidak menggunakan cahaya murni, melainkan kekuatan iblis kuno yang diwarisi secara misterius. Setiap kali ia menyembuhkan luka, bayangan hitam berdenyut di sekitarnya, seolah menghisap sakit lalu menukarnya menjadi kehidupan. Meski dicurigai banyak orang, ia tetap berjalan di jalannya sendiri—menjadi jembatan antara kegelapan dan harapan.",
	"en":"A beautiful elf woman gifted from childhood with the talent to heal, yet unlike her kin, she wields not pure light but the ancient power of demons passed down in mystery. Each time she mends a wound, dark shadows pulse around her, as if absorbing pain and reshaping it into life. Though distrusted by many, she chooses her own path—standing as a bridge between darkness and hope."
}
var hero_28 = {
	"id":"Seorang iblis cantik berdarah setengah elf, lahir dengan bakat luar biasa sebagai pendukung. Dari kecil ia menyadari kehadirannya mampu memengaruhi orang di sekitarnya, memberi mereka kekuatan yang tak pernah dimiliki sebelumnya. Dengan sihir misterius yang mengalir dari garis keturunannya, ia dapat mengubah satu pasukan biasa menjadi kekuatan menakutkan. Meski sering dianggap berbahaya, ia memilih perannya sendiri: bukan di garis depan, tapi sebagai jiwa yang mengangkat seluruh pasukan.",
	"en":"A beautiful half-elf demon, born with extraordinary talent as a supporter. From childhood, she realized her presence alone could empower those around her, granting strength they never possessed. Through mysterious magic inherited from her bloodline, she can transform an ordinary army into a terrifying force. Though often seen as dangerous, she chooses her own role—not on the frontlines, but as the soul that uplifts an entire legion."
}
var hero_29 = {
	"id":"Ia adalah saudari dari iblis setengah elf yang berbakat sebagai pendukung, namun kekuatannya berkembang ke arah berbeda. Sejak kecil, ia selalu melindungi saudarinya yang dianggap berbahaya, hingga tumbuh menjadi perisai sekaligus bayangan yang setia. Jika saudarinya mampu memberi kekuatan pada satu pasukan, maka ia menjadi tangan yang memastikan kekuatan itu digunakan tanpa sia-sia. Bersama, mereka membentuk keseimbangan: satu memberi kehidupan, satu menjaga agar kehidupan itu tidak hancur.",
	"en":"She is the sister of the half-elf demon gifted in support, yet her power grew along a different path. From childhood, she defended her sister—branded dangerous—becoming both shield and loyal shadow. If her sister can empower an army, she is the hand that ensures that strength is never wasted. Together, they form a balance: one who grants life, and one who safeguards it from destruction."
}
var hero_30 = {
	"id":"Iblis kuat ini diciptakan untuk garis depan pertempuran, tubuhnya dipenuhi senjata alami. Pedang besar di tangan dipadukan dengan cakar tajam di tangan dan kakinya, menjadikannya mesin perang yang sempurna. Sayap gelap di punggungnya bukan hanya lambang kekuasaan, tapi juga alat untuk menerjang lawan dari udara dengan keganasan tak terbendung. Setiap gerakannya meninggalkan jejak kehancuran, menjadikannya benteng sekaligus tombak bagi pasukannya.",
	"en":"This powerful demon was forged for the frontlines, its body a living arsenal. A massive sword in its hand, claws sharpened on both hands and feet, make it the perfect war machine. The dark wings on its back are not mere symbols of power, but tools to strike from the skies with unstoppable ferocity. Each movement leaves a trail of ruin, making it both shield and spear for its army."
}
var hero_31 = {
	"id":"Iblis ini tampil menyeramkan dengan kepala berbentuk tengkorak, kosong namun dipenuhi aura mengerikan. Ekor panjang yang melilit di belakangnya bukan hanya hiasan, melainkan senjata mematikan yang dapat menghantam, mencekik, atau menusuk musuh tanpa ampun. Sejak kelahirannya, ia dianggap sebagai lambang kematian berjalan, sosok yang menghadirkan rasa putus asa hanya dengan kehadirannya. Dalam setiap langkahnya, bayangan seolah ikut membeku.",
	"en":"This demon appears terrifying with a skull-shaped head, hollow yet radiating dreadful aura. Its long tail trailing behind is no mere appendage but a lethal weapon—capable of striking, strangling, or piercing its foes mercilessly. From birth, it was seen as a walking emblem of death, a figure that brings despair by presence alone. With each step, even the shadows seem to freeze in fear."
}
var hero_32 = {
	"id":"Seorang prajurit iblis cantik, tubuhnya ramping namun penuh kekuatan mematikan. Sejak kecil ia ditempa dalam medan perang, hingga tombak merah di tangannya menjadi bagian dari jiwanya. Tombak itu bukan sekadar senjata, melainkan simbol darah dan sumpahnya untuk terus bertarung. Setiap tebasan dan tusukan mampu menembus pertahanan terkeras. Dalam sorot matanya, kecantikan berpadu dengan keganasan, menjadikannya prajurit yang ditakuti sekaligus dikagumi.",
	"en":"A beautiful demon warrior, her slender form conceals deadly might. Raised on the battlefield since childhood, the crimson spear she wields has become part of her very soul. More than a weapon, it is a symbol of blood and an oath to fight without end. Each strike and thrust can pierce the strongest defenses. In her gaze, beauty intertwines with ferocity, making her both feared and admired."
}
var hero_33 = {
	"id":"Raja iblis api ini menjulang gagah, tubuhnya dipenuhi bara yang seolah tak pernah padam. Pedang satu tangan yang membara di genggamannya bukan hanya senjata, melainkan perwujudan amarahnya. Sayap hitam berlapis api mengibarkan ketakutan di medan perang, setiap kepakannya meninggalkan jejak hangus. Sejak lahir ia hidup di dalam api, belajar bahwa hanya kobaran panas dan kekuatan mutlak yang bisa memastikan kekuasaan abadi. Ia adalah badai api yang menjelma raja.",
	"en":"This demon king of fire stands imposing, his body wreathed in eternal flames. The blazing one-handed sword he wields is not just a weapon, but the embodiment of his fury. His dark wings, veined with fire, spread terror across the battlefield, each beat scorching the earth. Born in fire, he learned that only heat and absolute strength could secure everlasting dominion. He is the inferno incarnate, a king forged in flame."
}
var hero_35 = {
	"id":"Seorang iblis wanita cantik yang dikenal sebagai penyihir dengan kekuatan ungu yang mengerikan. Sejak kecil ia haus akan pengetahuan terlarang, hingga menemukan sihir purba yang hanya bisa dikuasai dengan pengorbanan jiwa. Aura ungu yang mengelilinginya mampu meremukkan pikiran, melumpuhkan tubuh, bahkan menelan cahaya. Kecantikannya hanyalah tirai bagi kekuatan yang bisa memutarbalikkan medan perang. Ia bukan sekadar penyihir, melainkan simbol kegelapan yang elegan dan tak terbantahkan.",
	"en":"A beautiful demon woman, known as a sorceress wielding terrifying violet magic. Since childhood, she craved forbidden knowledge, eventually mastering ancient spells that demanded sacrifices of the soul. The violet aura surrounding her can shatter minds, cripple bodies, and even devour light itself. Her beauty is merely a veil for power capable of twisting the battlefield. She is not just a sorceress, but an elegant embodiment of undeniable darkness."
}
var hero_36 = {
	"id":"Seorang raja dari semua penyihir, ditakuti sekaligus dihormati, karena kekuatan tak terbatas sudah tertanam di dadanya sejak lahir. Dari kecil, ia tidak pernah membutuhkan guru—sihir seolah mengalir alami dari jantungnya, memancar sebagai sumber energi purba. Setiap mantra yang ia ucapkan mampu mengubah medan perang, menelan musuh, atau membentuk ulang realitas. Namun di balik kejayaan itu, dadanya terus berdenyut dengan beban kutukan, seakan kekuatan itu bukan hanya anugerah, melainkan penjara.",
	"en":"The king of all sorcerers, feared and revered, for limitless power has been embedded within his chest since birth. From childhood, he needed no teacher—magic flowed naturally from his heart, radiating as an ancient source of energy. Every spell he uttered could reshape battlefields, consume enemies, or bend reality itself. Yet behind such glory, his chest pulsed with the weight of a curse, as though that power were not only a gift, but also a prison."
}
var hero_37 = {
	"id":"Makhluk ini adalah hibrida menyerupai manusia, namun bersisik merah menyala seperti kadal api. Dari tubuhnya menjuntai rantai membara, setiap hembusan napasnya memercikkan bara. Posturnya tegak layaknya prajurit, tetapi gerakannya lincah dan liar. Sejak diciptakan melalui eksperimen terlarang, ia menjadi simbol kemarahan dan kehancuran. Rantai api yang digenggamnya mampu membakar apa pun, menjadikannya penjagal sekaligus penegak kegelapan di medan perang.",
	"en":"This creature is a hybrid, human-like yet covered in blazing red scales of a fire lizard. Chains of fire hang from its body, each breath scattering sparks. Its stance is upright like a warrior, but its movements are swift and feral. Born from forbidden experiments, it became a symbol of wrath and destruction. The fiery chains it wields can burn through anything, making it both executioner and enforcer of darkness on the battlefield."
}
var hero_38 = {
	"id":"Seorang penyihir api wanita cantik, auranya memancarkan pesona sekaligus ancaman. Sejak kecil ia bermain dengan bara, hingga api menjadi bagian dari jiwanya. Tangan halusnya mampu menyalakan kobaran yang dapat melindungi ataupun menghancurkan. Banyak yang terpesona oleh kecantikannya, hanya untuk tersadar bahwa di balik senyum manisnya tersembunyi kobaran neraka. Ia adalah keindahan yang menyala, api yang menari di antara kasih dan kehancuran.",
	"en":"A beautiful fire sorceress, her presence radiates both allure and menace. Since childhood she has danced with flames, until fire became part of her very soul. Her delicate hands can summon blazes to protect or to annihilate. Many fall for her beauty, only to realize too late that behind her gentle smile burns an inferno. She is living fire itself—beauty ablaze, balancing between warmth and ruin."
}
var hero_39 = {
	"id":"Seorang prajurit roh api yang tubuhnya berkilau seperti bara hidup. Kekuatan utamanya bukan hanya dalam serangan, melainkan dalam aura yang membakar jiwa orang-orang di sekitarnya. Siapa pun yang berada dekat dengannya akan merasakan aliran panas yang mempercepat gerakan, membuat pasukan biasa berubah menjadi badai serangan cepat. Ia lahir dari semangat pertempuran kuno, roh api yang tidak hanya bertarung sendiri, tapi mengobarkan kekuatan seluruh pasukannya.",
	"en":"A warrior spirit of fire, his body gleams like living embers. His true strength lies not only in combat but in the aura that ignites those around him. Anyone near feels a blazing surge that sharpens reflexes and accelerates movements, turning ordinary soldiers into a storm of swift strikes. Born from the ancient will of battle, he is a fire spirit who fights not alone, but as the burning heart that empowers his entire army."
}
var hero_40 = {
	"id":"Roh api terkuat ini menjelma dengan sepuluh tangan yang menyala bagai obor abadi. Setiap tangannya memancarkan kekuatan berbeda, dari nyala perlindungan hingga kobaran yang mempercepat gerakan dan memperkuat serangan. Di tengah pertempuran, kehadirannya bagaikan matahari kedua, membuat pasukan di sekitarnya terbakar semangat dan kekuatan yang tak terbendung. Ia bukan sekadar prajurit, melainkan jantung api yang mengubah barisan lemah menjadi kekuatan legendaris.",
	"en":"The strongest fire spirit manifests with ten blazing hands, each burning like an eternal torch. Every hand radiates a different power—flames of protection, surges of speed, or infernos that enhance attacks. On the battlefield, his presence is like a second sun, igniting allies with unstoppable strength and fervor. He is more than a warrior; he is the heart of fire itself, transforming fragile ranks into a legendary force."
}
var hero_41 = {
	"id":"Dulu ia adalah seorang biksu yang mencari kedamaian, namun api balas dendam membakar jiwanya hingga ia menjelma menjadi prajurit api. Tubuhnya kini diselimuti bara, rantai merah panas melilit di tangannya sebagai senjata sekaligus belenggu. Kemanusiaannya telah hilang, wajahnya hanya menyisakan bayangan amarah dan penderitaan. Ia bukan lagi penjaga kedamaian, melainkan roh perang yang terus membakar dunia, dihantui masa lalunya sendiri.",
	
}
var hero_42 = {
	"id":"Seorang anak kecil yang kehilangan segalanya akibat perang, tubuhnya hangus oleh api kebencian. Dari trauma itu lahirlah perubahan mengerikan—ia menjelma menjadi monster prajurit api. Matanya tak lagi memancarkan kepolosan, melainkan kobaran amarah tanpa akhir. Di tangannya sebuah kapak dengan kepala membara, setiap ayunannya adalah teriakan jiwa yang pernah hancur. Ia bukan lagi anak yang lemah, melainkan penjelmaan dendam yang membakar dunia di sekitarnya.",
	"en":"A child who lost everything to war, his body scorched by the flames of hatred. From that trauma came a horrific transformation—he became a fire warrior monster. His eyes no longer hold innocence, but an endless blaze of wrath. In his hands rests an axe with a flaming head, every swing a cry from the shattered soul he once was. No longer the weak child, he is vengeance incarnate, setting the world aflame around him."
}
var hero_43 = {
	"id":"Di medan perang, seorang prajurit kuat gugur dengan tubuh yang hancur namun jiwa yang masih menyala. Dari reruntuhan pertempuran, roh api misterius turun dan mengambil alih raganya. Api itu menyatu dengan sisa tubuhnya, menghidupkan kembali sosok yang kini bukan sepenuhnya manusia, bukan pula roh murni. Setiap langkahnya membawa bara yang mengintimidasi kawan dan lawan, sebuah pengingat bahwa bahkan dalam kematian, api perang tak pernah padam.",
	"en":"On the battlefield, a mighty warrior fell, his body broken yet his spirit still burning. From the ashes of war, a mysterious fire spirit descended and claimed his form. The flames fused with his remains, reviving a being no longer fully human, nor purely spirit. Each step radiates embers that strike fear into friend and foe alike—a living reminder that even in death, the fire of war never dies."
}
var hero_44 = {
	"id":"Dulu ia adalah seorang bangsawan dari negeri cahaya, pewaris darah malaikat yang dihormati. Namun, keserakahannya akan kekuasaan membuatnya menggadaikan jiwa pada iblis api. Perjanjian terkutuk itu menghancurkan nuraninya, menghapus kesadarannya, dan menjadikannya sekadar boneka perang. Tubuhnya kini dibakar api neraka, kekuatan malaikat dalam dirinya berubah menjadi senjata penghancur. Ia bukan lagi simbol kebajikan, melainkan pengingat pahit tentang jatuhnya seorang pewaris cahaya ke dalam kegelapan abadi.",
	"en":"Once a noble of the realm of light, he was heir to angelic power and honor. Yet his greed for dominion led him to bargain his soul with a fire demon. That cursed pact shattered his conscience, stripping away his will, leaving him a puppet of war. His body burns with infernal fire, the angelic gift within him twisted into a weapon of destruction. No longer a symbol of virtue, he stands as a grim reminder of an heir of light fallen into eternal darkness."
}
var hero_71 = {
	"id":"Darah manusia dan serigala mengalir dalam dirinya, menjadikannya sosok penyihir api yang berbeda dari yang lain. Dari kecil ia ditolak karena dianggap kutukan, namun api dalam dirinya terus tumbuh, bergejolak setiap kali amarahnya meledak. Saat bulan merah bersinar, sihir apinya bercampur dengan naluri buas serigala, menghasilkan kobaran yang sulit dikendalikan. Kini ia berjalan di antara dua dunia, sebagai penyihir yang ditakuti sekaligus makhluk liar yang tidak bisa sepenuhnya disebut manusia.",
	"en":"Human blood mixed with that of a wolf flows within, shaping him into a fire sorcerer unlike any other. As a child, he was shunned as a curse, yet the flames inside kept growing, erupting whenever his rage surfaced. Under the red moon, his fire magic merges with the beastly instincts of the wolf, unleashing an inferno beyond control. Now he walks between two worlds—a feared sorcerer, yet a feral being who can no longer be called fully human."
}
var hero_72 = {
	"id":"Dulu ia hanyalah seorang warga desa yang dibantai habis oleh para penjarah. Tubuhnya terkoyak, namun jiwanya menolak lenyap. Dari penderitaan itu lahirlah roh terkutuk, bangkit dengan wujud tengkorak yang diselubungi sihir hitam. Kini ia menjadi penyihir tulang, menjaga desa yang pernah hancur dengan kekuatan mengerikan. Namun, setiap mantranya adalah jeritan dari masa lalunya, sebuah pengingat bahwa ia bertahan bukan karena hidup, melainkan karena dendam yang tak pernah padam.",
	"en":"Once an ordinary villager slaughtered by raiders, his body was torn apart—but his soul refused to die. From that torment rose a cursed spirit, reborn as a skeletal sorcerer shrouded in dark magic. Now he stands as the guardian of the ruined village, wielding terrifying power. Yet every spell he casts carries the echo of his suffering, a reminder that he endures not through life, but through vengeance that can never fade."
}
var hero_73 = {
	"id":"Api yang seharusnya melahap tubuh kecil itu berubah jadi pelindung. Saat teriakan pengorbanan terdengar, roh api merasakan iba yang tak pernah ia kenal. Ia merelakan jiwanya melebur, menukar keabadian dengan hidup seorang anak. Dari bara itu lahir prajurit yang membawa luka abadi—setiap percikan api di tubuhnya adalah kenangan tentang nyala yang dulu ingin membunuhnya, kini menjadi alasan untuk melawan kegelapan.",
	"en":"The flames meant to consume the fragile child became a shield instead. As the cry of sacrifice echoed, the fire spirit felt pity it had never known. It surrendered its soul, trading eternity for the child’s life. From those ashes rose a warrior scarred forever—every spark upon their body a memory of fire once meant to kill them, now turned into the reason they fight against the darkness."
}
var hero_74 = {
	"id":"Ia hanyalah penyihir kesepian yang hidupnya terikat pada satu-satunya teman: roh api kecil yang kian meredup. Ketika bara itu hampir padam, ia membuat pilihan terlarang—menjual jiwanya pada iblis, agar nyala sahabatnya tak pernah hilang. Kini keduanya menyatu, menjadi prajurit api yang kekuatannya lahir dari cinta yang getir. Namun setiap kali ia memanggil kobaran itu, terdengar bisikan gelap yang menuntut bayaran abadi.",
	"en":"Once a lonely sorcerer bound only to a fading fire spirit, they faced the terror of losing the last fragment of companionship. As the ember weakened, a forbidden choice was made—selling their soul to a demon, so the flame would never vanish. Now, they are fused into one, a warrior of fire born from bittersweet devotion. Yet each time the blaze rises, a dark whisper echoes, demanding its eternal price."
}
var hero_75 = {
	"id":"Dari kobaran api persembahan yang haus darah, lahirlah sesuatu yang tak pernah diramalkan. Terlalu banyak jiwa manusia dilemparkan ke dalam nyala, hingga bara itu tak lagi sekadar api, melainkan rahim gelap yang menetas makhluk baru. Separuh manusia, separuh naga, ia tumbuh dengan jeritan ribuan jiwa yang terkunci dalam darahnya. Setiap hembusan napas api yang keluar adalah doa terputus, kutukan yang tak pernah berhenti bernyanyi.",
	"en":"From the flames of sacrificial pyres came a birth never foretold. Too many human souls were cast into the blaze, until the fire ceased to be mere flame and became a dark womb. Half human, half dragon, it rose carrying the screams of thousands bound within its veins. Every breath of fire it exhales is a severed prayer, a curse that sings without end."
}
