class_name Data_story_bab_en
var data_bab_story = {
	"bab_1":{
		"stage_1":{
			"header":"",
			"story":""
		},"stage_2":{
			"header":"",
			"story":""
		},"stage_3":{
			"header":"",
			"story":""
		},"stage_4":{
			"header":"",
			"story":""
		},"stage_5":{
			"header":"",
			"story":""
		},"stage_6":{
			"header":"",
			"story":""
		},"stage_7":{
			"header":"",
			"story":""
		},"stage_8":{
			"header":"",
			"story":""
		},"stage_9":{
			"header":"",
			"story":""
		},"stage_10":{
			"header":"",
			"story":""
		},"stage_11":{
			"header":"",
			"story":""
		},"stage_12":{
			"header":"",
			"story":""
		},
	},"bab_2":{
		"stage_1":{
			"header":"",
			"story":""
		},"stage_2":{
			"header":"",
			"story":""
		},"stage_3":{
			"header":"",
			"story":""
		},"stage_4":{
			"header":"",
			"story":""
		},"stage_5":{
			"header":"",
			"story":""
		},"stage_6":{
			"header":"",
			"story":""
		},"stage_7":{
			"header":"",
			"story":""
		},"stage_8":{
			"header":"",
			"story":""
		},"stage_9":{
			"header":"",
			"story":""
		},"stage_10":{
			"header":"",
			"story":""
		},"stage_11":{
			"header":"",
			"story":""
		},"stage_12":{
			"header":"",
			"story":""
		},
	},"bab_3":{
		"stage_1":{
			"header":"",
			"story":""
		},"stage_2":{
			"header":"",
			"story":""
		},"stage_3":{
			"header":"",
			"story":""
		},"stage_4":{
			"header":"",
			"story":""
		},"stage_5":{
			"header":"",
			"story":""
		},"stage_6":{
			"header":"",
			"story":""
		},"stage_7":{
			"header":"",
			"story":""
		},"stage_8":{
			"header":"",
			"story":""
		},"stage_9":{
			"header":"",
			"story":""
		},"stage_10":{
			"header":"",
			"story":""
		},"stage_11":{
			"header":"",
			"story":""
		},"stage_12":{
			"header":"",
			"story":""
		},
	},"bab_4":{
		"stage_1":{
			"header":"",
			"story":""
		},"stage_2":{
			"header":"",
			"story":""
		},"stage_3":{
			"header":"",
			"story":""
		},"stage_4":{
			"header":"",
			"story":""
		},"stage_5":{
			"header":"",
			"story":""
		},"stage_6":{
			"header":"",
			"story":""
		},"stage_7":{
			"header":"",
			"story":""
		},"stage_8":{
			"header":"",
			"story":""
		},"stage_9":{
			"header":"",
			"story":""
		},"stage_10":{
			"header":"",
			"story":""
		},"stage_11":{
			"header":"",
			"story":""
		},"stage_12":{
			"header":"",
			"story":""
		},
	},"bab_5":{
		"stage_1":{
			"header":"",
			"story":""
		},"stage_2":{
			"header":"",
			"story":""
		},"stage_3":{
			"header":"",
			"story":""
		},"stage_4":{
			"header":"",
			"story":""
		},"stage_5":{
			"header":"",
			"story":""
		},"stage_6":{
			"header":"",
			"story":""
		},"stage_7":{
			"header":"",
			"story":""
		},"stage_8":{
			"header":"",
			"story":""
		},"stage_9":{
			"header":"",
			"story":""
		},"stage_10":{
			"header":"",
			"story":""
		},"stage_11":{
			"header":"",
			"story":""
		},"stage_12":{
			"header":"",
			"story":""
		},
	},"bab_6":{
		"stage_1":{
			"header":"",
			"story":""
		},"stage_2":{
			"header":"",
			"story":""
		},"stage_3":{
			"header":"",
			"story":""
		},"stage_4":{
			"header":"",
			"story":""
		},"stage_5":{
			"header":"",
			"story":""
		},"stage_6":{
			"header":"",
			"story":""
		},"stage_7":{
			"header":"",
			"story":""
		},"stage_8":{
			"header":"",
			"story":""
		},"stage_9":{
			"header":"",
			"story":""
		},"stage_10":{
			"header":"",
			"story":""
		},"stage_11":{
			"header":"",
			"story":""
		},"stage_12":{
			"header":"",
			"story":""
		},
	},"bab_7":{
		"stage_1":{
			"header":"",
			"story":""
		},"stage_2":{
			"header":"",
			"story":""
		},"stage_3":{
			"header":"",
			"story":""
		},"stage_4":{
			"header":"",
			"story":""
		},"stage_5":{
			"header":"",
			"story":""
		},"stage_6":{
			"header":"",
			"story":""
		},"stage_7":{
			"header":"",
			"story":""
		},"stage_8":{
			"header":"",
			"story":""
		},"stage_9":{
			"header":"",
			"story":""
		},"stage_10":{
			"header":"",
			"story":""
		},"stage_11":{
			"header":"",
			"story":""
		},"stage_12":{
			"header":"",
			"story":""
		},
	},
}
