class_name Data_setcard
var data_allcard_player = {
	"tier_1":{
		"light":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"nature":{
			"warrior":["s1_000"],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":["s1_001"],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":["s1_002"]
		},
		"water":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"dark":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"fire":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		}
	},
	"tier_2":{
		"light":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"nature":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"water":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"dark":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":["s1_003"],
			"healer":[]
		},
		"fire":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		}
	},
	"tier_3":{
		"light":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"nature":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"water":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"dark":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"fire":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		}
	},
	"tier_4":{
		"light":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"nature":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"water":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"dark":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"fire":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		}
	},
	"tier_5":{
		"light":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"nature":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"water":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"dark":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"fire":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		}
	},
	"tier_6":{
		"light":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"nature":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"water":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"dark":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"fire":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		}
	},
}
var data_allcard_npc = {
	"tier_1":{
		"light":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"nature":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"water":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"dark":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"fire":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		}
	},
	"tier_2":{
		"light":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"nature":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"water":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"dark":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"fire":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		}
	},
	"tier_3":{
		"light":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"nature":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"water":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"dark":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"fire":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		}
	},
	"tier_4":{
		"light":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"nature":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"water":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"dark":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"fire":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		}
	},
	"tier_5":{
		"light":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"nature":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"water":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"dark":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"fire":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		}
	},
	"tier_6":{
		"light":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"nature":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"water":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"dark":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		},
		"fire":{
			"warrior":[],
			"archer":[],
			"defender":[],
			"assasin":[],
			"support":[],
			"mecha":[],
			"beast":[],
			"mage":[],
			"healer":[]
		}
	},
}
