class_name data_story_en

var main_data = {
	"bab_1":"At the edge of a quiet village lies a dense forest, forever veiled in mist so thick that even daylight seems reluctant to enter. Towering trees stand close together, their roots gripping the soil like ancient claws, while the damp air carries the scent of endless decay and growth. The forest thrives with an unsettling vitality, as though it harbors secrets too old to name. Villagers believe that anyone who wanders too far leaves behind only a name, vanishing without a trace as if the silence itself consumes them. To them, the forest is no myth, but a living mystery cloaked in fog.",
	"bab_2":"Amid a barren wasteland scorched by relentless sun, the sands stretch endlessly, hostile to all who wander them. Yet beyond the shifting dunes rises a colossal fortress, its towering walls defying both time and desert storms. Within those walls thrives a hidden city—narrow streets, stone dwellings, and markets alive with sound—an oasis of survival carved against despair. For the remnants of humanity, the fortress is the last refuge, the final bastion shielding fragile life from a desert determined to erase every trace of civilization.",
	"bab_3":"On a frozen expanse where silence reigns, every breath feels stolen from the thin air that clings to life itself. The endless sheets of ice conceal veins of gold locked in frozen stone, coal buried deep beneath permafrost, and mana crystals that glimmer faintly as though alive. This land carries the weight of an ancient secret, a mystery sealed beneath its eternal frost. Yet the cold is merciless, the storms relentless, and the lack of oxygen turns the terrain into a natural tomb for any who dare to seek what lies hidden beneath the ice.",
	"bab_4":"Deep within the bowels of the earth lies a realm almost untouched by human presence. Eternal darkness cloaks the caverns, broken only by the faint glow of luminous minerals and rivers of underground water that glimmer like obsidian glass. Vast forests of towering fungi stretch across the stone, while strange creatures without eyes move through the silence, guided by instincts unknown. It is a world apart, alien yet alive, carrying whispers from depths unfathomable. A hidden life thrives in the abyss, guarding secrets that may never be meant for the surface to uncover.",
	"bab_5":"Behind towering walls and smoke-filled spires lies a city ruled by mad science. Every street echoes with the grinding of gears, the crackle of electricity, and the chaos of endless experiments. Laboratories crowd the avenues, each birthing creations born from ambition unchecked by morality. From the shadows emerge twisted hybrids—part machine, part flesh—living testaments to brilliance tangled with obsession. This city is a cradle of invention and insanity alike, where progress and nightmare intertwine, and the line between genius and madness has long since vanished.",
	"bab_6":"High above the clouds rises a sky kingdom, radiating beauty as though carved from a dream. Towers of crystal and gleaming metal catch the sunlight, scattering brilliance across the heavens. Floating pathways connect luminous bridges, while hanging gardens overflow with blossoms that never fade. Great birds and winged creatures soar freely, guardians of this celestial domain. From such heights, the world below appears distant and small, like a faint shadow beneath eternity. It is a realm of majesty and harmony, a paradise suspended in the endless blue of the sky.",
	"bab_7":"Between fractured dimensions lies an ancient dominion, whispered only as the throne of primordial demons. The gateway appears as a rift of living shadow, exhaling the stench of sulfur and voices that echo from endless dark. Obsidian citadels rise from the abyss, crowned with eternal flames that never wane, while colossal silhouettes prowl behind their walls. Within, the demon lords command powers bound to time and soul itself. This kingdom is not merely a place but a wound in the cosmos—an eternal mystery pulsing between realms, awaiting the lost to be devoured.",
}
